config/routes.rb
Rails.application.routes.draw do

  root controller: :questions, action: :index
  resources :questions, except: [:index, :show]

  resources :quiz, only: :show do
    member do
      patch :answer
    end
  end
end

app/models/answer.rb
class Answer < Struct.new(:value)
  def to_s
    value.to_s
  end

  def correct_with?(input)
    p1 = patterns_for(to_s)
    p2 = patterns_for(input.to_s)
    !(p1 & p2).empty?
  end

  private

  def patterns_for(str)
    list = [
      to_integer_or_float(str),
      str
    ].compact

    list.map! do |item|
      case item
      when Integer
        item.humanize
      when Float
        %i(digits number).map { |d| item.humanize(decimals_as: d) }
      when String
        item
      end
    end

    list.flatten
  end

  def to_integer_or_float(str)
    Integer(str)
  rescue ArgumentError
    begin
      Float(str)
    rescue ArgumentError
      nil
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :content, presence: true
  validates :answer, presence:true

  def correct_answer?(input)
    Answer.new(answer).correct_with?(input)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    if @question.save
      redirect_to root_url, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    if @question.update(question_params)
      redirect_to root_url, notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    redirect_to root_url, notice: 'Question was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :answer)
    end
end

app/controllers/quiz_controller.rb
class QuizController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_question, only: [:show, :answer]

  def show
    @react_data = @question.as_json(only: :content).merge(url: answer_quiz_url(@question))
  end

  # PATCH /questions/1/answer
  def answer
    if @question.correct_answer?(answer_params[:answer])
      render json: { result: 'correct', message: 'Congrats! Your answer is correct!' }
    else
      render json: { result: 'incorrect', message: 'Oooops, incorrect... orz' }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def answer_params
      params.require(:question).permit(:answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | QuizMaster
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = stylesheet_link_tag    'https://fonts.googleapis.com/icon?family=Material+Icons', media: 'all'
    = javascript_include_tag 'application'
  body
    header
      nav
        .nav-wrapper
          a.brand-logo.center href='/'
            | Quiz Master
    main
    .container.padding-top-2ex
      - flash.each do |type, message|
        - color = (type == 'error') ? 'red' : 'blue'
        = javascript_tag "Materialize.toast('#{message}', 4000, '#{color}')"
      - flash.clear
      = yield
    footer.page-footer
      .container.padding-top-2ex
        .footer-copylight.grey-text
          | Copyright © 2017 nalabjp All Rights Reserved

app/views/questions/_form.html.slim
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      h6.red-text.text-darken-4 = "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      ul
        - @question.errors.full_messages.each do |message|
          li.red-text = message
  .input-field
    = f.text_field :content, class: 'validate'
    = f.label :content
  .input-field
    = f.text_field :answer, class: 'validate'
    = f.label :answer
  .row
    .col.s6.input-field
      .right
        = f.submit 'Submit', class: 'btn z-depth-3'
    .col.s6.input-field
      = link_to 'Back', root_path, class: 'btn z-depth-3'

app/views/questions/edit.html.slim
h5 Editing question

== render 'form'

app/views/questions/index.html.slim
h5 Which question do you challenge?

ul.collection.margin-top-5ex
  - @questions.each do |q|
    li.collection-item
      = link_to q.content, quiz_path(q)
      .right
        .inline
          = link_to edit_question_path(q)
            i.material-icons
              | mode_edit
        .inline.margin-left-1em
          = link_to q, data: { confirm: 'Are you sure?' }, method: :delete do
            i.material-icons
              | delete

.center-align
  = link_to 'Create New Question', new_question_path, class: 'btn z-depth-3 margin-top-2ex'

app/views/questions/new.html.slim
h5 Create new question

== render 'form'

app/views/questions/show.html.slim
h5 Question

h4
  = @question.content
= form_for @question, url: { action: :answer } do |f|
  .input-field
    = f.text_field :answer, value: '', class: 'validate'
    = f.label :answer
  .row
    .col.s6.input-field
      .right
        = f.submit 'Submit', class: 'btn z-depth-3'
    .col.s6.input-field
      = link_to 'Back', root_path, class: 'btn z-depth-3'

app/views/quiz/show.html.slim
h5 Question

= react_component('QuizForm', @react_data)